[project]
name = "sql-qa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain[openai]>=0.3.27",
    "langchain-community>=0.3.29",
    "langgraph>=0.6.6",
    "dotenv>=0.9.9",
    "langsmith>=0.4.21",
]
